name: Beymen & SauceDemo Cross-Browser UI Automation CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Manuel tetikleme kök hizada, canavar gibi çalışır.

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodları GitHub deposundan sanal makineye çek
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Uzak makineye Java 25 kurulumu yap
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      # 3. Bağımlılıkları ve Çapraz Tarayıcıları (Browsers) Sunucuya Kur
      - name: Install Google Chrome, Firefox and Edge
        run: |
          sudo apt-get update
          
          # Chrome Kurulumu
          sudo apt-get install -y google-chrome-stable
          
          # Firefox Güncellemesi (Ubuntu'da yüklü gelen Snap yapısını korur)
          sudo apt-get install --only-upgrade -y firefox || true
          
          # Edge Kurulumu (O sinsi .by hatası tamamen .d olarak düzeltildi!)
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
          rm microsoft.gpg
          sudo apt-get update && sudo apt-get install -y microsoft-edge-stable

      # 4. Tarayıcıları arayüzlü (headed) taklit edebilmek için sanal ekran kartını (Xvfb) aç
      - name: Start Xvfb (Virtual Display)
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      # 5. Testleri koştur
      - name: Run Automation Tests
        run: mvn clean test

      # 6. Allure sonuçlarını koru ve harika raporu üret
      - name: Load Allure History & Generate Report
        uses: simple-elf/allure-report-action@master
        if: always() # Testler fail olsa bile raporun üretilmesi için şart!
        with:
          allure_results: target/allure-results
          allure_report: allure-report
          allure_history: allure-history

      # 7. Üretilen Allure raporunu Artifact olarak GitHub paneline yükle
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report